server:
  serverName: 'butterfly-monitor'
  engineMode: 'release'
  serverAddr: :8081

auth:
  ignorePath:
    - POST - /run
    - POST - /kill
    - POST - /log
    - GET - /api/monitor/test
    - POST - /api/notify
  ignorePrefixPath:
  commonPath:

influx:
  addr: http://127.0.0.1:8086
  database: monitor

xxl:
  accessToken: xxl
  serverAddr: http://127.0.0.1:8080/xxl-job-admin

grafana:
  sampleRpName: expire_7d
  addr: http://127.0.0.1:3000
  apiKey: eyJrIjoiN2ZTb0txTTQ3Q3BQZ3p5OVU3NXZNRGFkSGl5Qm1pZ0EiLCJuIjoic3VwZXJhZG1pbiIsImlkIjoxfQ==