db:
  dsn: 'root:root@tcp(127.0.0.1:3306)/butterfly_monitor?charset=utf8mb4&parseTime=True&loc=Local'

server:
  serverName: 'butterfly-monitor'
  engineMode: 'release'
  serverAddr: :8081

auth:
  ignorePath:
    - POST - /run
    - POST - /kill
    - POST - /log
    - GET - /api/monitor/test
    - POST - /api/notify
  ignorePrefixPath:
  commonPath:

influx:
  addr: http://127.0.0.1:8086
  database: monitor

xxl:
  accessToken: xxl

grafana:
  addr: http://localhost:3000
  apiKey: eyJrIjoiYk1Tc1NMazB6M3VyOEJqVkdzeDlpcmZhZ1dCZmg4R0UiLCJuIjoiYWRtaW4iLCJpZCI6MX0=