db:
  dsn: 'root:root@tcp(localhost:3306)/butterfly_monitor?charset=utf8mb4&parseTime=True&loc=Local'

influx:
  addr: http://localhost:8086
  database: monitor

xxl:
  accessToken: xxl
  serverAddr: http://localhost:8080/xxl-job-admin

grafana:
  sampleRpName: expire_30d
  addr: http://localhost:3000
  clientId: 314626c1-8500-e1dd-a8c3-d6753fc4a6bb
  secret: cae30a08-1912-ea19-14a0-42300477be35
  apiKey: eyJrIjoiZ0lHcDRYbkd6b05kUUh4cldGR1VqQ0tkbktsaTh0M3AiLCJuIjoic3VwZXIiLCJpZCI6MX0=