server:
  serverName: 'butterfly-monitor'
  engineMode: 'test'
  serverAddr: :8081

auth:
  ignorePath:
    - POST - /run
    - POST - /kill
    - POST - /log
    - GET - /api/monitor/test
    - GET - /api/health
  ignorePrefixPath:
  commonPath: