server:
  serverName: 'butterfly-monitor'
  engineMode: 'test'
  serverAddr: :8081

auth:
  ignorePath:
    - POST - /run
    - POST - /kill
    - POST - /log
    - GET - /api/monitor/test
    - GET - /api/health
    - GET - /api/sys/menu/withOption
    - GET - /api/sys/role/all
    - GET - /api/alert/channel/all
    - GET - /api/alert/group/all
    - GET - /api/monitor/dashboard/all
    - GET - /api/monitor/database/all
  ignorePrefixPath:
  commonPath: